### ISSUE TITLE
Lifetimes do not match method in trait

### ISSUE THREAD

**Issue by simonsan** [slawlor/ractor#217]
**Describe the bug**

When you copy one of the examples or in general use the 'implement missing members' of `rust-analyzer` you'll get `error[E0195]: lifetime parameters or bounds on method '<method>' do not match the trait declaration`. This could be related to the removal of `async_trait`, I assume?

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy example into crates `main.rs`
2. run `cargo check`
4. See above error.

**Expected behaviour**
It works without manually researching on the error.

**Additional context**

```console
rustc --version --verbose

rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-msvc
release: 1.76.0
LLVM version: 17.0.6
```

```toml
[package]
name = "actor-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# ractor = "0.9" -> doesn't work either
ractor = { git = "https://github.com/slawlor/ractor", branch = "main" }
rand = "0.8.5"
tokio = { version = "1.36.0", default-features = false, features = ["rt-multi-thread"] }
tracing = "0.1.40"
tracing-glog = "0.3.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
```

- Example used: https://github.com/slawlor/ractor/blob/main/ractor/examples/monte_carlo.rs
